import type { Metadata } from 'next';

import { absoluteUrl, site } from './site';

type PageMetaInput = {
  title: string;
  description: string;
  /** Site-relative path, e.g. /pdf/merge */
  path: string;
  keywords?: string[];
};

/**
 * Builds title/description/canonical/OG/Twitter for a page in one place so no
 * route can ship with a missing canonical or a duplicated description.
 */
export function pageMetadata({
  title,
  description,
  path,
  keywords,
}: PageMetaInput): Metadata {
  const url = absoluteUrl(path);

  // The branded card generated by app/opengraph-image.tsx. Named explicitly
  // because a route that sets its own `openGraph` object no longer inherits
  // the file convention.
  const ogImage = {
    url: absoluteUrl('/opengraph-image'),
    width: 1200,
    height: 630,
    alt: `${site.name} — ${site.oneLiner}`,
  };

  return {
    title,
    description,
    keywords,
    alternates: { canonical: url },
    openGraph: {
      type: 'website',
      url,
      siteName: site.name,
      title,
      description,
      images: [ogImage],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}
