/**
 * Generates `lib/icons.generated.ts` from the names in `icon-names.mjs`.
 *
 * Pulls each icon's artwork out of `@material-symbols/svg-400`, strips the
 * wrapper `<svg>` (the Icon component supplies its own, so size and colour are
 * controlled by the caller), and writes the inner markup into a typed map.
 *
 * Both the outline and the filled variant are emitted so the Icon component's
 * `filled` prop is real rather than a CSS approximation.
 *
 * A name that does not exist in the package throws, so a typo fails the build
 * instead of shipping an invisible icon.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ICONS } from './icon-names.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const source = join(root, 'node_modules', '@material-symbols', 'svg-400', 'outlined');
const target = join(root, 'lib', 'icons.generated.ts');

/** Everything inside the root <svg>, with the viewBox normalised to 0 0 24 24. */
function extractBody(file) {
  const svg = readFileSync(file, 'utf8');

  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
  if (!viewBox) throw new Error(`No viewBox in ${file}`);

  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  if (!body) throw new Error(`Empty icon body in ${file}`);

  return { viewBox, body: body.replace(/\s+/g, ' ') };
}

const entries = [];
const missing = [];

for (const [key, name] of Object.entries(ICONS)) {
  try {
    const outline = extractBody(join(source, `${name}.svg`));
    let filled = null;
    try {
      filled = extractBody(join(source, `${name}-fill.svg`)).body;
    } catch {
      // Not every symbol ships a filled variant; the outline stands in.
    }
    entries.push({ key, name, ...outline, filled });
  } catch (error) {
    missing.push(`${key} -> ${name} (${error.message})`);
  }
}

if (missing.length > 0) {
  console.error(`\n${missing.length} icon(s) could not be resolved:`);
  for (const line of missing) console.error(`  ${line}`);
  console.error('\nFix the names in scripts/icon-names.mjs.\n');
  process.exit(1);
}

const body = entries
  .map(
    (entry) =>
      `  ${entry.key}: {\n` +
      `    viewBox: '${entry.viewBox}',\n` +
      `    path: ${JSON.stringify(entry.body)},\n` +
      (entry.filled ? `    filled: ${JSON.stringify(entry.filled)},\n` : '') +
      `  },`,
  )
  .join('\n');

const output = `/**
 * GENERATED by scripts/build-icons.mjs — do not edit.
 *
 * Google Material Symbols (Apache 2.0), inlined for exactly the icons this app
 * uses. Edit scripts/icon-names.mjs and re-run the script to change the set.
 */

export type IconGlyph = {
  viewBox: string;
  path: string;
  filled?: string;
};

export const ICON_PATHS = {
${body}
} as const satisfies Record<string, IconGlyph>;

export type IconName = keyof typeof ICON_PATHS;
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, output);

const bytes = Buffer.byteLength(output);
console.log(
  `icons: ${entries.length} generated (${entries.filter((e) => e.filled).length} with a filled variant), ${(bytes / 1024).toFixed(1)} kB`,
);
